[package]
name = "rust_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_affinity = { "version" = "0.5.10" }
perf-event = "0.4.8"

[profile.release]
# strip = true
